const bcrypt = require('bcryptjs');
const mongoose = require('mongoose');

const User = require('./modules/user/user.model');
const Category = require('./modules/category/category.model');
const Product = require('./modules/product/product.model');
const Banner = require('./modules/banner/banner.model');
const Coupon = require('./modules/coupon/coupon.model');
const Address = require('./modules/address/address.model');
const Order = require('./modules/order/order.model');
const Review = require('./modules/review/review.model');
const Cart = require('./modules/cart/cart.model');
const Wishlist = require('./modules/wishlist/wishlist.model');
const Notification = require('./modules/notification/notification.model');

async function seedData() {
  // Clear existing collections
  await Promise.all([
    User.deleteMany({}),
    Category.deleteMany({}),
    Product.deleteMany({}),
    Banner.deleteMany({}),
    Coupon.deleteMany({}),
    Address.deleteMany({}),
    Order.deleteMany({}),
    Review.deleteMany({}),
    Cart.deleteMany({}),
    Wishlist.deleteMany({}),
    Notification.deleteMany({}),
  ]);

  console.log('[seed] Cleared old records...');

  // 1. Create Users
  const env = require('./config/env');
  const passwordHash = await bcrypt.hash(env.adminSeed.password, 10);
  const userPasswordHash = await bcrypt.hash('User@123', 10);

  const admin = await User.create({
    name: 'AMA-YAAR Admin',
    email: env.adminSeed.email.toLowerCase(),
    password: passwordHash,
    role: 'admin',
    phone: '+91 9876543210',
    status: 'active',
  });

  const demoUser = await User.create({
    name: 'Rahul Sharma',
    email: 'user@ama-yaar.com',
    password: userPasswordHash,
    role: 'customer',
    phone: '+91 9811223344',
    status: 'active',
  });

  console.log('[seed] Created admin and demo user...');

  // 2. Create Addresses for demo user
  const address1 = await Address.create({
    user: demoUser._id,
    fullName: 'Rahul Sharma',
    phone: '+91 9811223344',
    line1: 'Flat 402, Sunshine Heights, MG Road',
    line2: 'Near Central Mall',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560001',
    country: 'India',
    addressType: 'Home',
    isDefault: true,
  });

  const address2 = await Address.create({
    user: demoUser._id,
    fullName: 'Rahul Sharma (Office)',
    phone: '+91 9811223344',
    line1: 'Tech Park Tower B, 5th Floor, Outer Ring Rd',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560103',
    country: 'India',
    addressType: 'Work',
    isDefault: false,
  });

  await User.findByIdAndUpdate(demoUser._id, {
    addresses: [address1._id, address2._id],
  });

  // 3. Create Categories
  const catFashion = await Category.create({
    name: 'Fashion',
    slug: 'fashion',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&q=80',
    isActive: true,
  });

  const catElectronics = await Category.create({
    name: 'Electronics',
    slug: 'electronics',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&q=80',
    isActive: true,
  });

  const catHome = await Category.create({
    name: 'Home & Living',
    slug: 'home-and-living',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80',
    isActive: true,
  });

  const catBeauty = await Category.create({
    name: 'Beauty & Wellness',
    slug: 'beauty-and-wellness',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80',
    isActive: true,
  });

  const catSports = await Category.create({
    name: 'Sports & Fitness',
    slug: 'sports-and-fitness',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&q=80',
    isActive: true,
  });

  const catWatches = await Category.create({
    name: 'Watches & Accessories',
    slug: 'watches-and-accessories',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
    isActive: true,
  });

  // Subcategories
  const subMen = await Category.create({ name: 'Men', slug: 'fashion-men', parent: catFashion._id });
  const subWomen = await Category.create({ name: 'Women', slug: 'fashion-women', parent: catFashion._id });
  const subFootwear = await Category.create({ name: 'Footwear', slug: 'fashion-footwear', parent: catFashion._id });

  const subAudio = await Category.create({ name: 'Audio & Sound', slug: 'electronics-audio', parent: catElectronics._id });
  const subMobiles = await Category.create({ name: 'Mobiles & Tablets', slug: 'electronics-mobiles', parent: catElectronics._id });
  const subComputers = await Category.create({ name: 'Laptops & Computers', slug: 'electronics-computers', parent: catElectronics._id });

  const subFurniture = await Category.create({ name: 'Furniture', slug: 'home-furniture', parent: catHome._id });
  const subKitchen = await Category.create({ name: 'Kitchen & Dining', slug: 'home-kitchen', parent: catHome._id });

  const subSkincare = await Category.create({ name: 'Skincare', slug: 'beauty-skincare', parent: catBeauty._id });
  const subFragrances = await Category.create({ name: 'Fragrances', slug: 'beauty-fragrances', parent: catBeauty._id });

  const subFitness = await Category.create({ name: 'Fitness Equipment', slug: 'sports-fitness', parent: catSports._id });
  const subSportsGear = await Category.create({ name: 'Sports Gear', slug: 'sports-gear', parent: catSports._id });

  const subSmartwatches = await Category.create({ name: 'Smartwatches', slug: 'watches-smart', parent: catWatches._id });
  const subLuxuryWatches = await Category.create({ name: 'Luxury Watches', slug: 'watches-luxury', parent: catWatches._id });

  console.log('[seed] Created category tree...');

  // 4. Create Products
  const productsData = [
    {
      name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
      slug: 'sony-wh-1000xm5-wireless-noise-canceling-headphones',
      description: 'Industry-leading noise cancellation with two processors and 8 microphones. Ultra-comfortable lightweight design with soft fit leather. Up to 30-hour battery life with quick charging.',
      brand: 'Sony',
      category: catElectronics._id,
      subCategory: subAudio._id,
      images: [
        'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
        'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80',
        'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
      ],
      price: 24990,
      mrp: 34990,
      discount: 29,
      stock: 35,
      rating: 4.8,
      numReviews: 124,
      isFeatured: true,
      isBestSeller: true,
      isTrending: true,
      variants: [
        { color: 'Silver', stock: 15, sku: 'SONY-XM5-SLV' },
        { color: 'Midnight Black', stock: 20, sku: 'SONY-XM5-BLK' },
      ],
      specifications: [
        { name: 'Driver Unit', value: '30 mm, Dome type' },
        { name: 'Battery Life', value: '30 hours (NC ON)' },
        { name: 'Connectivity', value: 'Bluetooth 5.2, 3.5mm Aux' },
        { name: 'Weight', value: '250g' },
      ],
      highlights: ['Industry-Leading Active Noise Cancellation', 'Crystal Clear Hands-Free Calling', 'Multipoint Connection (2 Devices)', 'Ultra-Fast Quick Charge'],
      tags: ['audio', 'headphones', 'sony', 'wireless', 'anc'],
    },
    {
      name: 'Apple MacBook Air M3 Chip 15-inch Liquid Retina Display',
      slug: 'apple-macbook-air-m3-15-inch',
      description: 'Supercharged by the next-generation M3 chip, the redesigned MacBook Air 15 combines incredible performance and up to 18 hours of battery life in a strikingly thin aluminum enclosure.',
      brand: 'Apple',
      category: catElectronics._id,
      subCategory: subComputers._id,
      images: [
        'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
        'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&q=80',
      ],
      price: 134900,
      mrp: 144900,
      discount: 7,
      stock: 12,
      rating: 4.9,
      numReviews: 89,
      isFeatured: true,
      isTrending: true,
      variants: [
        { color: 'Space Grey', size: '512GB SSD / 16GB RAM', stock: 6, sku: 'MBA-M3-15-SG' },
        { color: 'Midnight Blue', size: '512GB SSD / 16GB RAM', stock: 6, sku: 'MBA-M3-15-MID' },
      ],
      specifications: [
        { name: 'Processor', value: 'Apple M3 chip (8-core CPU / 10-core GPU)' },
        { name: 'Memory', value: '16GB Unified Memory' },
        { name: 'Storage', value: '512GB NVMe SSD' },
        { name: 'Display', value: '15.3-inch Liquid Retina (2880 x 1864)' },
      ],
      highlights: ['Next-Gen M3 Processor', '18 Hours Battery Life', '1080p FaceTime HD Camera', 'MagSafe 3 Charging'],
      tags: ['apple', 'macbook', 'laptop', 'm3', 'premium'],
    },
    {
      name: 'Samsung Galaxy S24 Ultra 5G AI Smartphone',
      slug: 'samsung-galaxy-s24-ultra-5g',
      description: 'Meet Galaxy S24 Ultra with Galaxy AI, titanium frame, 200MP camera system with ProVisual engine, and built-in S Pen.',
      brand: 'Samsung',
      category: catElectronics._id,
      subCategory: subMobiles._id,
      images: [
        'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
        'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&q=80',
      ],
      price: 119999,
      mrp: 134999,
      discount: 11,
      stock: 20,
      rating: 4.7,
      numReviews: 64,
      isFeatured: true,
      variants: [
        { color: 'Titanium Gray', size: '256GB', stock: 10, sku: 'S24U-TGR-256' },
        { color: 'Titanium Black', size: '512GB', stock: 10, sku: 'S24U-TBK-512' },
      ],
      specifications: [
        { name: 'Processor', value: 'Snapdragon 8 Gen 3 for Galaxy' },
        { name: 'Primary Camera', value: '200MP + 50MP + 12MP + 10MP' },
        { name: 'Battery', value: '5000 mAh with 45W Fast Charging' },
      ],
      highlights: ['Galaxy AI Built-in', 'Titanium Shield Armor', '200MP Ultra Pro Camera', 'Built-in S Pen Stylus'],
      tags: ['samsung', 'smartphone', '5g', 'galaxy'],
    },
    {
      name: 'Nike Air Max 270 React Running Shoes',
      slug: 'nike-air-max-270-react-running-shoes',
      description: 'The Nike Air Max 270 React merges artistic design with cutting-edge comfort. Features a lightweight Nike React foam midsole and oversized 270 Max Air unit in the heel.',
      brand: 'Nike',
      category: catFashion._id,
      subCategory: subFootwear._id,
      images: [
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
        'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?w=800&q=80',
      ],
      price: 6995,
      mrp: 10995,
      discount: 36,
      stock: 40,
      rating: 4.6,
      numReviews: 210,
      isBestSeller: true,
      isTrending: true,
      variants: [
        { size: 'UK 7', color: 'Crimson Red / White', stock: 10, sku: 'NKE-AM270-07' },
        { size: 'UK 8', color: 'Crimson Red / White', stock: 15, sku: 'NKE-AM270-08' },
        { size: 'UK 9', color: 'Crimson Red / White', stock: 15, sku: 'NKE-AM270-09' },
      ],
      specifications: [
        { name: 'Material', value: 'Breathable Mesh & Synthetic' },
        { name: 'Sole', value: 'React Foam + Max Air Heel' },
        { name: 'Closure', value: 'Speed Lacing System' },
      ],
      highlights: ['Max Air 270 Heel Cushioning', 'Ultra-lightweight React Foam', 'Durable Rubber Outsole'],
      tags: ['nike', 'shoes', 'running', 'sneakers', 'fashion'],
    },
    {
      name: 'Premium Oxford Slim-Fit Cotton Shirt',
      slug: 'premium-oxford-slim-fit-cotton-shirt',
      description: 'Crafted from 100% long-staple Egyptian cotton, this crisp button-down Oxford shirt offers enduring elegance, breathability, and seamless wrinkle resistance for the modern gentleman.',
      brand: 'Raymond',
      category: catFashion._id,
      subCategory: subMen._id,
      images: [
        'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80',
        'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
      ],
      price: 1899,
      mrp: 3299,
      discount: 42,
      stock: 60,
      rating: 4.5,
      numReviews: 78,
      isNewArrival: true,
      variants: [
        { size: 'M', color: 'Classic Sky Blue', stock: 20, sku: 'SHIRT-M-BLU' },
        { size: 'L', color: 'Classic Sky Blue', stock: 25, sku: 'SHIRT-L-BLU' },
        { size: 'XL', color: 'Classic Sky Blue', stock: 15, sku: 'SHIRT-XL-BLU' },
      ],
      specifications: [
        { name: 'Fabric', value: '100% Combed Pure Cotton' },
        { name: 'Fit', value: 'Tailored Slim Fit' },
        { name: 'Collar', value: 'Button-Down Oxford Collar' },
      ],
      highlights: ['100% Pure Egyptian Cotton', 'Wrinkle-Resistant Weave', 'Mother-of-Pearl Finish Buttons'],
      tags: ['men', 'shirt', 'cotton', 'formal', 'fashion'],
    },
    {
      name: 'Minimalist Scandinavian Solid Teak Wood Lounge Chair',
      slug: 'minimalist-scandinavian-solid-teak-lounge-chair',
      description: 'Hand-finished solid teak wood chair with high-density ergonomic foam cushioning and neutral linen upholstery. A stunning accent piece for living spaces and studies.',
      brand: 'UrbanLiving',
      category: catHome._id,
      subCategory: subFurniture._id,
      images: [
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
        'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80',
      ],
      price: 14499,
      mrp: 22999,
      discount: 37,
      stock: 15,
      rating: 4.9,
      numReviews: 32,
      isFeatured: true,
      variants: [
        { color: 'Natural Walnut & Beige', stock: 8, sku: 'CHR-WAL-BGE' },
        { color: 'Teak & Charcoal Grey', stock: 7, sku: 'CHR-TEK-GRY' },
      ],
      specifications: [
        { name: 'Material', value: 'Grade-A Seasoned Teak Wood' },
        { name: 'Fabric', value: 'Water-Repellent Breathable Linen' },
        { name: 'Dimensions', value: '78cm x 72cm x 82cm' },
      ],
      highlights: ['100% Solid Seasoned Wood Frame', 'Ergonomic Curved Backrest', 'Anti-Scratch Floor Protectors'],
      tags: ['furniture', 'chair', 'decor', 'scandinavian', 'home'],
    },
    {
      name: 'Cast Iron Dutch Oven 5.5 Quart Enamelled Pot',
      slug: 'cast-iron-dutch-oven-5-5-quart',
      description: 'Heavy-duty enameled cast iron delivers superior heat distribution and retention for slow cooking, braising, baking artisan sourdough breads, and stews.',
      brand: 'ChefCraft',
      category: catHome._id,
      subCategory: subKitchen._id,
      images: [
        'https://images.unsplash.com/photo-1584990347449-34b8c9fb605e?w=800&q=80',
        'https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=800&q=80',
      ],
      price: 3999,
      mrp: 6499,
      discount: 38,
      stock: 25,
      rating: 4.8,
      numReviews: 45,
      isTrending: true,
      variants: [
        { color: 'Ceramic Cherry Red', stock: 15, sku: 'DUTCH-RED-55' },
        { color: 'Cobalt Navy Blue', stock: 10, sku: 'DUTCH-BLU-55' },
      ],
      specifications: [
        { name: 'Capacity', value: '5.5 Quarts (5.2 Litres)' },
        { name: 'Heat Tolerance', value: 'Up to 260°C / 500°F (Oven Safe)' },
        { name: 'Coating', value: 'Multi-Layer Glass Enamel' },
      ],
      highlights: ['Even Heat Distribution & Retention', 'Oven Safe Up to 500°F', 'Compatible with Induction & Gas'],
      tags: ['kitchen', 'cookware', 'cast-iron', 'dutch-oven'],
    },
    {
      name: 'Luxury Botanical Radiance Face Serum (Vitamin C + Hyaluronic)',
      slug: 'luxury-botanical-radiance-face-serum',
      description: 'Potent 15% Vitamin C combined with botanical hyaluronic acid and ferulic acid to brighten dark spots, even skin tone, and deeply hydrate without grease.',
      brand: 'AuraBotanics',
      category: catBeauty._id,
      subCategory: subSkincare._id,
      images: [
        'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80',
        'https://images.unsplash.com/photo-1608248597359-0524458f44ff?w=800&q=80',
      ],
      price: 1249,
      mrp: 2499,
      discount: 50,
      stock: 80,
      rating: 4.7,
      numReviews: 142,
      isBestSeller: true,
      isNewArrival: true,
      variants: [
        { size: '30ml Dropper', stock: 50, sku: 'SRM-30ML' },
        { size: '50ml Value Pack', stock: 30, sku: 'SRM-50ML' },
      ],
      specifications: [
        { name: 'Skin Type', value: 'All Skin Types (Dermatologist Tested)' },
        { name: 'Key Ingredients', value: '15% Ethyl Ascorbic Acid, 2% Hyaluronic Acid' },
        { name: 'Formulation', value: '100% Vegan, Cruelty-Free, Paraben-Free' },
      ],
      highlights: ['Visibly Brightens Skin in 14 Days', '24-Hour Deep Hydration Lock', '100% Clean Organic Formulation'],
      tags: ['skincare', 'serum', 'beauty', 'vitamin-c', 'radiance'],
    },
    {
      name: 'Floral Print Chiffon Maxi Dress',
      slug: 'floral-print-chiffon-maxi-dress',
      description: 'Elegantly styled bohemian maxi dress featuring an ethereal floral pattern, soft tiered skirt, V-neckline, and comfortable elasticated waist. Perfect for casual outings and summer parties.',
      brand: 'Zara',
      category: catFashion._id,
      subCategory: subWomen._id,
      images: [
        'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80',
        'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&q=80',
      ],
      price: 2999,
      mrp: 4999,
      discount: 40,
      stock: 30,
      rating: 4.6,
      numReviews: 54,
      isNewArrival: true,
      isTrending: true,
      variants: [
        { size: 'S', color: 'Pastel Floral', stock: 10, sku: 'DRESS-S-FLR' },
        { size: 'M', color: 'Pastel Floral', stock: 10, sku: 'DRESS-M-FLR' },
        { size: 'L', color: 'Pastel Floral', stock: 10, sku: 'DRESS-L-FLR' },
      ],
      specifications: [
        { name: 'Material', value: '100% Chiffon Polyester' },
        { name: 'Sleeve Length', value: 'Three-Quarter Sleeves' },
        { name: 'Care Instructions', value: 'Machine Wash Cold' },
      ],
      highlights: ['Lightweight Breathable Chiffon Fabric', 'Flattering Tiered Silhouette', 'Inner Soft Lining Included'],
      tags: ['women', 'dress', 'maxi', 'floral', 'fashion'],
    },
    {
      name: 'Oversized Classic Denim Trucker Jacket',
      slug: 'oversized-classic-denim-trucker-jacket',
      description: 'Iconic vintage-wash denim jacket crafted from heavyweight cotton denim. Features dual chest pockets, button-down closure, and adjustable waist tabs for a timeless casual aesthetic.',
      brand: "Levi's",
      category: catFashion._id,
      subCategory: subWomen._id,
      images: [
        'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&q=80',
        'https://images.unsplash.com/photo-1525457136159-8878648a7ad0?w=800&q=80',
      ],
      price: 3499,
      mrp: 5999,
      discount: 41,
      stock: 25,
      rating: 4.7,
      numReviews: 68,
      isBestSeller: true,
      variants: [
        { size: 'S', color: 'Vintage Light Blue', stock: 8, sku: 'JCKT-S-LBLU' },
        { size: 'M', color: 'Vintage Light Blue', stock: 10, sku: 'JCKT-M-LBLU' },
        { size: 'L', color: 'Vintage Light Blue', stock: 7, sku: 'JCKT-L-LBLU' },
      ],
      specifications: [
        { name: 'Fabric', value: '100% Heavyweight Cotton Denim' },
        { name: 'Closure', value: 'Metal Button Placket' },
        { name: 'Fit', value: 'Relaxed Oversized Fit' },
      ],
      highlights: ['100% Premium Cotton Denim', 'Durable Reinforced Stitching', 'Classic 4-Pocket Layout'],
      tags: ['women', 'denim', 'jacket', 'levis', 'fashion'],
    },
    {
      name: 'Adidas Ultraboost 1.0 Running Sneakers',
      slug: 'adidas-ultraboost-1-0-running-sneakers',
      description: 'Experience exceptional energy return with Adidas Ultraboost 1.0 featuring Primeknit upper, responsive BOOST midsole, and Continental Rubber outsole for supreme grip.',
      brand: 'Adidas',
      category: catFashion._id,
      subCategory: subFootwear._id,
      images: [
        'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80',
        'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80',
      ],
      price: 11999,
      mrp: 17999,
      discount: 33,
      stock: 35,
      rating: 4.8,
      numReviews: 112,
      isFeatured: true,
      isBestSeller: true,
      variants: [
        { size: 'UK 8', color: 'Core Black', stock: 12, sku: 'ADI-UB-08' },
        { size: 'UK 9', color: 'Core Black', stock: 15, sku: 'ADI-UB-09' },
        { size: 'UK 10', color: 'Core Black', stock: 8, sku: 'ADI-UB-10' },
      ],
      specifications: [
        { name: 'Upper Material', value: 'Adidas Primeknit Textile' },
        { name: 'Midsole', value: 'Full-length BOOST Cushioning' },
        { name: 'Outsole', value: 'Continental™ Rubber Outsole' },
      ],
      highlights: ['Responsive BOOST Cushioning', 'Adaptive Primeknit Upper', 'Continental Rubber Outsole Traction'],
      tags: ['adidas', 'ultraboost', 'sneakers', 'running', 'footwear'],
    },
    {
      name: 'Handcrafted Genuine Leather Chelsea Boots',
      slug: 'handcrafted-genuine-leather-chelsea-boots',
      description: 'Classic ankle-length Chelsea boots made from premium full-grain leather with elastic side goring and a sturdy stacked heel. Provides high durability and refined style.',
      brand: 'Woodland',
      category: catFashion._id,
      subCategory: subFootwear._id,
      images: [
        'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80',
        'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80',
      ],
      price: 4999,
      mrp: 7999,
      discount: 37,
      stock: 20,
      rating: 4.5,
      numReviews: 42,
      isTrending: true,
      variants: [
        { size: 'UK 8', color: 'Tan Brown', stock: 8, sku: 'BOOT-8-TAN' },
        { size: 'UK 9', color: 'Tan Brown', stock: 7, sku: 'BOOT-9-TAN' },
        { size: 'UK 10', color: 'Tan Brown', stock: 5, sku: 'BOOT-10-TAN' },
      ],
      specifications: [
        { name: 'Upper Material', value: '100% Genuine Full-Grain Leather' },
        { name: 'Sole Material', value: 'Thermoplastic Rubber (TPR)' },
        { name: 'Insole', value: 'Cushioned Memory Foam' },
      ],
      highlights: ['100% Genuine Grain Leather', 'Easy Slip-On Elastic Goring', 'Slip-Resistant TPR Sole'],
      tags: ['boots', 'leather', 'chelsea', 'footwear', 'fashion'],
    },
    {
      name: 'Slim Fit Stretch Denim Jeans 511',
      slug: 'slim-fit-stretch-denim-jeans-511',
      description: 'Modern slim fit jeans crafted with room to move. Made with high-performance stretch denim for all-day flexibility, comfort, and timeless indigo style.',
      brand: "Levi's",
      category: catFashion._id,
      subCategory: subMen._id,
      images: [
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
        'https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=800&q=80',
      ],
      price: 2799,
      mrp: 4499,
      discount: 37,
      stock: 45,
      rating: 4.6,
      numReviews: 95,
      isBestSeller: true,
      variants: [
        { size: '30 Waist', color: 'Dark Indigo Wash', stock: 15, sku: 'LEV-511-30' },
        { size: '32 Waist', color: 'Dark Indigo Wash', stock: 18, sku: 'LEV-511-32' },
        { size: '34 Waist', color: 'Dark Indigo Wash', stock: 12, sku: 'LEV-511-34' },
      ],
      specifications: [
        { name: 'Material', value: '99% Cotton, 1% Elastane' },
        { name: 'Fly', value: 'Zip Fly with Button Closure' },
        { name: 'Fit', value: 'Slim Through Thigh & Leg' },
      ],
      highlights: ['Premium Stretch Flex Denim', 'Classic 5-Pocket Design', 'Durable Metal Rivets'],
      tags: ['men', 'jeans', 'levis', 'denim', 'fashion'],
    },
    {
      name: 'Genuine Faux Leather Biker Jacket',
      slug: 'genuine-faux-leather-biker-jacket',
      description: 'Edgy moto biker jacket featuring asymmetrical front zipper, lapel collar with snap studs, multiple zippered pockets, and quilted shoulder panel detailing.',
      brand: 'Roadster',
      category: catFashion._id,
      subCategory: subMen._id,
      images: [
        'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80',
        'https://images.unsplash.com/photo-1520975954732-35dd22299614?w=800&q=80',
      ],
      price: 3299,
      mrp: 5999,
      discount: 45,
      stock: 22,
      rating: 4.4,
      numReviews: 38,
      isNewArrival: true,
      variants: [
        { size: 'M', color: 'Matte Black', stock: 10, sku: 'BIKER-M-BLK' },
        { size: 'L', color: 'Matte Black', stock: 8, sku: 'BIKER-L-BLK' },
        { size: 'XL', color: 'Matte Black', stock: 4, sku: 'BIKER-XL-BLK' },
      ],
      specifications: [
        { name: 'Material', value: '100% Polyurethane Outer, Polyester Lining' },
        { name: 'Closure', value: 'Heavy Duty YKK Zipper' },
        { name: 'Pockets', value: '3 Exterior Zip Pockets, 1 Inner Pocket' },
      ],
      highlights: ['Asymmetrical Biker Zip Design', 'Quilted Shoulder Padding', 'Windproof Warm Fabric'],
      tags: ['men', 'jacket', 'leather', 'biker', 'fashion'],
    },
    {
      name: 'Bose QuietComfort Ultra Wireless Noise-Cancelling Earbuds',
      slug: 'bose-quietcomfort-ultra-wireless-earbuds',
      description: 'World-class active noise cancellation paired with Bose Immersive Audio. CustomTune technology personalizes sound to fit your unique ear shape for maximum clarity.',
      brand: 'Bose',
      category: catElectronics._id,
      subCategory: subAudio._id,
      images: [
        'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80',
        'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80',
      ],
      price: 21900,
      mrp: 25900,
      discount: 15,
      stock: 18,
      rating: 4.7,
      numReviews: 76,
      isFeatured: true,
      isTrending: true,
      variants: [
        { color: 'Black', stock: 10, sku: 'BOSE-QC-BLK' },
        { color: 'White Smoke', stock: 8, sku: 'BOSE-QC-WHT' },
      ],
      specifications: [
        { name: 'Battery Life', value: 'Up to 6 hours (24h total with case)' },
        { name: 'Water Resistance', value: 'IPX4 Splash-Proof' },
        { name: 'Bluetooth', value: 'Bluetooth 5.3 with Multipoint' },
      ],
      highlights: ['Revolutionary Spatial Immersive Audio', 'CustomTune Sound Personalization', 'IPX4 Sweat & Weather Resistant'],
      tags: ['bose', 'earbuds', 'audio', 'wireless', 'anc'],
    },
    {
      name: 'JBL Charge 5 Waterproof Portable Bluetooth Speaker',
      slug: 'jbl-charge-5-waterproof-portable-bluetooth-speaker',
      description: 'Deliver bold JBL Original Pro Sound with optimized long excursion driver, separate tweeter, and dual JBL bass radiators. Up to 20 hours of playtime and built-in powerbank.',
      brand: 'JBL',
      category: catElectronics._id,
      subCategory: subAudio._id,
      images: [
        'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
        'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80',
      ],
      price: 13999,
      mrp: 18999,
      discount: 26,
      stock: 30,
      rating: 4.8,
      numReviews: 140,
      isBestSeller: true,
      variants: [
        { color: 'Squad Camo', stock: 15, sku: 'JBL-CHG5-CAM' },
        { color: 'Midnight Blue', stock: 15, sku: 'JBL-CHG5-BLU' },
      ],
      specifications: [
        { name: 'Output Power', value: '40W RMS' },
        { name: 'Playtime', value: '20 Hours' },
        { name: 'Waterproof Rating', value: 'IP67 Dust & Waterproof' },
      ],
      highlights: ['Bold JBL Original Pro Sound', '20 Hours Playtime', 'IP67 Dustproof & Waterproof', 'Built-in Powerbank Function'],
      tags: ['jbl', 'speaker', 'bluetooth', 'audio', 'waterproof'],
    },
    {
      name: 'Google Pixel 8 Pro 5G (Obsidian, 128GB)',
      slug: 'google-pixel-8-pro-5g',
      description: 'Powered by Google Tensor G3 with advanced AI. Features a brilliant 6.7-inch Super Actua display, fully upgraded triple camera system, and 7 years of OS updates.',
      brand: 'Google',
      category: catElectronics._id,
      subCategory: subMobiles._id,
      images: [
        'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=80',
        'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80',
      ],
      price: 89999,
      mrp: 106999,
      discount: 15,
      stock: 14,
      rating: 4.6,
      numReviews: 52,
      isFeatured: true,
      variants: [
        { color: 'Obsidian Black', size: '128GB', stock: 8, sku: 'PX8P-OBS-128' },
        { color: 'Bay Blue', size: '256GB', stock: 6, sku: 'PX8P-BAY-256' },
      ],
      specifications: [
        { name: 'Processor', value: 'Google Tensor G3' },
        { name: 'Display', value: '6.7-inch Super Actua OLED 120Hz' },
        { name: 'Camera', value: '50MP Main + 48MP Ultrawide + 48MP Telephoto' },
      ],
      highlights: ['Google Tensor G3 Chip', 'Pro Camera Controls & Best Take', '7 Years of OS & Security Updates'],
      tags: ['google', 'pixel', 'smartphone', '5g', 'android'],
    },
    {
      name: 'OnePlus 12 5G (Silky Black, 16GB RAM, 512GB)',
      slug: 'oneplus-12-5g',
      description: 'Smooth Beyond Belief. Powered by Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera System for Mobile, 2K 120 Hz ProXDR Display, and 100W SUPERVOOC Fast Charging.',
      brand: 'OnePlus',
      category: catElectronics._id,
      subCategory: subMobiles._id,
      images: [
        'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&q=80',
        'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&q=80',
      ],
      price: 64999,
      mrp: 69999,
      discount: 7,
      stock: 22,
      rating: 4.7,
      numReviews: 88,
      isTrending: true,
      variants: [
        { color: 'Silky Black', size: '512GB / 16GB RAM', stock: 12, sku: 'OP12-BLK-512' },
        { color: 'Emerald Green', size: '512GB / 16GB RAM', stock: 10, sku: 'OP12-GRN-512' },
      ],
      specifications: [
        { name: 'Processor', value: 'Qualcomm Snapdragon 8 Gen 3' },
        { name: 'Charging', value: '100W SUPERVOOC Wired / 50W AIRVOOC' },
        { name: 'Battery', value: '5400 mAh Dual-Cell' },
      ],
      highlights: ['Snapdragon 8 Gen 3 Flagship', 'Hasselblad 4th Gen Camera', '100W Ultra-Fast Charging'],
      tags: ['oneplus', 'smartphone', '5g', 'flagship'],
    },
    {
      name: 'Dell XPS 13 Touchscreen Laptop (Intel Core Ultra 7)',
      slug: 'dell-xps-13-touchscreen-laptop',
      description: 'Precision crafted from CNC aluminum with glass palm rest. Features InfinityEdge QHD+ Touch display, Intel Core Ultra 7 processor, and up to 16 hours battery life.',
      brand: 'Dell',
      category: catElectronics._id,
      subCategory: subComputers._id,
      images: [
        'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&q=80',
        'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80',
      ],
      price: 149990,
      mrp: 169990,
      discount: 11,
      stock: 10,
      rating: 4.8,
      numReviews: 31,
      isFeatured: true,
      variants: [
        { color: 'Platinum Silver', size: '1TB SSD / 16GB RAM', stock: 5, sku: 'XPS13-SLV-1TB' },
        { color: 'Graphite', size: '1TB SSD / 16GB RAM', stock: 5, sku: 'XPS13-GRP-1TB' },
      ],
      specifications: [
        { name: 'Processor', value: 'Intel Core Ultra 7 155H' },
        { name: 'Display', value: '13.4-inch QHD+ (2560x1600) Touch OLED' },
        { name: 'Weight', value: '1.19 kg' },
      ],
      highlights: ['Ultra-Thin CNC Machined Aluminum', 'InfinityEdge OLED Touchscreen', 'Intel AI Boost Neural Engine'],
      tags: ['dell', 'xps', 'laptop', 'intel', 'premium'],
    },
    {
      name: 'ASUS ROG Zephyrus G14 Gaming Laptop (RTX 4060)',
      slug: 'asus-rog-zephyrus-g14-gaming-laptop',
      description: 'Ultra-portable 14-inch gaming laptop powered by AMD Ryzen 9 8945HS and NVIDIA GeForce RTX 4060. Features ROG Nebula OLED 120Hz display and AniMe Matrix LED lid.',
      brand: 'ASUS',
      category: catElectronics._id,
      subCategory: subComputers._id,
      images: [
        'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&q=80',
        'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&q=80',
      ],
      price: 154990,
      mrp: 174990,
      discount: 11,
      stock: 8,
      rating: 4.9,
      numReviews: 44,
      isTrending: true,
      variants: [
        { color: 'Eclipse Grey', size: '1TB SSD / 16GB DDR5', stock: 5, sku: 'ROG-G14-GRY' },
        { color: 'Moonlight White', size: '1TB SSD / 16GB DDR5', stock: 3, sku: 'ROG-G14-WHT' },
      ],
      specifications: [
        { name: 'Processor', value: 'AMD Ryzen 9 8945HS (8 Cores)' },
        { name: 'Graphics', value: 'NVIDIA GeForce RTX 4060 8GB GDDR6' },
        { name: 'Display', value: '14" 3K 120Hz 0.2ms ROG Nebula OLED' },
      ],
      highlights: ['NVIDIA RTX 4060 Graphics', '3K 120Hz ROG Nebula OLED', 'Ultra-Lightweight 1.5kg Chassis'],
      tags: ['asus', 'rog', 'gaming', 'laptop', 'rtx4060'],
    },
    {
      name: 'Ergonomic High-Back Executive Mesh Office Chair',
      slug: 'ergonomic-high-back-executive-mesh-office-chair',
      description: 'Designed for long working hours with 3D adjustable armrests, dynamic lumbar support, breathable Korean mesh, and 135-degree synchro-tilt lock mechanism.',
      brand: 'Green Soul',
      category: catHome._id,
      subCategory: subFurniture._id,
      images: [
        'https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=800&q=80',
        'https://images.unsplash.com/photo-1580481072645-022f9a6d8310?w=800&q=80',
      ],
      price: 9999,
      mrp: 17999,
      discount: 44,
      stock: 28,
      rating: 4.7,
      numReviews: 105,
      isBestSeller: true,
      variants: [
        { color: 'Full Black Mesh', stock: 18, sku: 'CHAIR-BLK-MSH' },
        { color: 'Grey & White Frame', stock: 10, sku: 'CHAIR-GRY-WHT' },
      ],
      specifications: [
        { name: 'Mechanism', value: 'Multi-Lock Heavy-Duty Synchro Tilt' },
        { name: 'Base', value: 'Class-4 Hydraulic Gas Lift & Nylon Base' },
        { name: 'Weight Capacity', value: 'Up to 135 kg' },
      ],
      highlights: ['Adaptive Adjustable Lumbar Support', '3D Soft Armrests', 'Breathable Heavy-Duty Mesh'],
      tags: ['office', 'chair', 'ergonomic', 'furniture', 'home'],
    },
    {
      name: 'Modern Minimalist Round Wooden Coffee Table',
      slug: 'modern-minimalist-round-wooden-coffee-table',
      description: 'Sleek contemporary coffee table crafted from solid oak wood top with matte black powder-coated steel legs. Fits seamlessly into modern living room decor.',
      brand: 'IKEA',
      category: catHome._id,
      subCategory: subFurniture._id,
      images: [
        'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=800&q=80',
        'https://images.unsplash.com/photo-1532323544230-7191fd51bc1b?w=800&q=80',
      ],
      price: 5499,
      mrp: 8999,
      discount: 38,
      stock: 16,
      rating: 4.6,
      numReviews: 29,
      isNewArrival: true,
      variants: [
        { color: 'Natural Oak Wood', stock: 10, sku: 'TBL-OAK-RND' },
        { color: 'Dark Walnut Finish', stock: 6, sku: 'TBL-WAL-RND' },
      ],
      specifications: [
        { name: 'Dimensions', value: '80cm Diameter x 45cm Height' },
        { name: 'Top Material', value: 'Solid Oak Wood Veneer' },
        { name: 'Leg Material', value: 'Powder-Coated Industrial Steel' },
      ],
      highlights: ['Solid Wooden Top Construction', 'Sturdy Powder-Coated Metal Legs', 'Scratch-Resistant Protective Finish'],
      tags: ['furniture', 'table', 'coffee-table', 'wooden', 'home'],
    },
    {
      name: "De'Longhi Magnifica Automatic Espresso & Cappuccino Machine",
      slug: 'delonghi-magnifica-automatic-espresso-machine',
      description: 'Bean-to-cup automatic espresso coffee maker with integrated silent steel burr grinder, patented LatteCrema frothing system, and one-touch custom drink presets.',
      brand: "De'Longhi",
      category: catHome._id,
      subCategory: subKitchen._id,
      images: [
        'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&q=80',
        'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80',
      ],
      price: 42999,
      mrp: 59999,
      discount: 28,
      stock: 12,
      rating: 4.9,
      numReviews: 63,
      isFeatured: true,
      variants: [
        { color: 'Silver Metallic', stock: 7, sku: 'DEL-MAG-SLV' },
        { color: 'Piano Black', stock: 5, sku: 'DEL-MAG-BLK' },
      ],
      specifications: [
        { name: 'Pump Pressure', value: '15 Bar Professional Pressure' },
        { name: 'Water Tank', value: '1.8 Litre Removable Tank' },
        { name: 'Grinder Settings', value: '13 Adjustable Burr Settings' },
      ],
      highlights: ['One-Touch Cappuccino & Latte', 'Integrated 13-Setting Burr Grinder', '15-Bar Italian Pump Pressure'],
      tags: ['coffee', 'espresso', 'kitchen', 'delonghi', 'appliances'],
    },
    {
      name: 'Philips XXL Digital Smart Air Fryer (7.2L Capacity)',
      slug: 'philips-xxl-digital-smart-air-fryer',
      description: 'Fry, bake, grill, roast and reheat with up to 90% less fat using Rapid CombiAir technology. Large 7.2L capacity easily feeds up to 6 people with connected NutriU app recipes.',
      brand: 'Philips',
      category: catHome._id,
      subCategory: subKitchen._id,
      images: [
        'https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80',
        'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80',
      ],
      price: 14999,
      mrp: 22995,
      discount: 34,
      stock: 25,
      rating: 4.8,
      numReviews: 120,
      isBestSeller: true,
      variants: [
        { color: 'Glossy Black / Rose Gold', stock: 15, sku: 'PHI-AF-XXL-BLK' },
        { color: 'Deep White', stock: 10, sku: 'PHI-AF-XXL-WHT' },
      ],
      specifications: [
        { name: 'Capacity', value: '7.2 Litres (1.4 kg batch)' },
        { name: 'Power', value: '2000 Watts' },
        { name: 'Programs', value: '22 Presets & Manual Temp Control' },
      ],
      highlights: ['Up to 90% Less Fat Cooking', '7.2L Family Size Capacity', 'Smart Sensing Auto Programs'],
      tags: ['airfryer', 'philips', 'kitchen', 'cooking', 'appliances'],
    },
    {
      name: 'Neutrogena Hydro Boost Water Gel Moisturizer',
      slug: 'neutrogena-hydro-boost-water-gel-moisturizer',
      description: 'Oil-free daily face gel moisturizer with Pure Hyaluronic Acid. Instantly quenches dry skin and locks in intense hydration for 72 hours without clogging pores.',
      brand: 'Neutrogena',
      category: catBeauty._id,
      subCategory: subSkincare._id,
      images: [
        'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
        'https://images.unsplash.com/photo-1617897903246-719242758050?w=800&q=80',
      ],
      price: 899,
      mrp: 1150,
      discount: 21,
      stock: 90,
      rating: 4.7,
      numReviews: 310,
      isBestSeller: true,
      variants: [
        { size: '50g Jar', stock: 50, sku: 'NEUT-HB-50G' },
        { size: '100g Value Tub', stock: 40, sku: 'NEUT-HB-100G' },
      ],
      specifications: [
        { name: 'Skin Type', value: 'Dry & Combination Skin' },
        { name: 'Key Ingredient', value: 'Hyaluronic Acid & Olive Extract' },
        { name: 'Formula', value: 'Non-Comedogenic & 100% Alcohol-Free' },
      ],
      highlights: ['72-Hour Continuous Hydration', 'Lightweight Oil-Free Water Gel', 'Dermatologist Recommended'],
      tags: ['skincare', 'moisturizer', 'neutrogena', 'beauty', 'hyaluronic'],
    },
    {
      name: 'Estée Lauder Advanced Night Repair Synchronized Multi-Recovery Complex',
      slug: 'estee-lauder-advanced-night-repair-serum',
      description: 'Deep-penetrating patented face serum that reduces the appearance of multiple signs of aging caused by environmental assaults of modern life. Skin looks smoother and less lined.',
      brand: 'Estée Lauder',
      category: catBeauty._id,
      subCategory: subSkincare._id,
      images: [
        'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?w=800&q=80',
        'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80',
      ],
      price: 6400,
      mrp: 7500,
      discount: 14,
      stock: 20,
      rating: 4.9,
      numReviews: 86,
      isFeatured: true,
      variants: [
        { size: '30ml Dropper', stock: 12, sku: 'EST-ANR-30' },
        { size: '50ml Dropper', stock: 8, sku: 'EST-ANR-50' },
      ],
      specifications: [
        { name: 'Key Tech', value: 'Chronolux™ Power Signal Technology' },
        { name: 'Benefits', value: 'Anti-Aging, Firming, Radiance & Hydration' },
        { name: 'Free From', value: 'Oil, Synthetic Fragrance, Parabens' },
      ],
      highlights: ['Number 1 Night Repair Serum', 'Visibly Reduces Lines & Wrinkles', '7-in-1 Nighttime Renewal Action'],
      tags: ['skincare', 'estee-lauder', 'serum', 'anti-aging', 'beauty'],
    },
    {
      name: 'Dior Sauvage Eau De Parfum Spray (100ml)',
      slug: 'dior-sauvage-eau-de-parfum-100ml',
      description: 'An authentically powerful fragrance featuring radiant Calabrian Bergamot and spicy Sichuan Pepper combined with precious Ambergris and warm Vanilla notes.',
      brand: 'Dior',
      category: catBeauty._id,
      subCategory: subFragrances._id,
      images: [
        'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80',
        'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80',
      ],
      price: 12500,
      mrp: 14000,
      discount: 10,
      stock: 15,
      rating: 4.9,
      numReviews: 175,
      isBestSeller: true,
      isTrending: true,
      variants: [
        { size: '100ml Spray Bottle', stock: 10, sku: 'DIOR-SAV-100' },
        { size: '200ml Refill Bottle', stock: 5, sku: 'DIOR-SAV-200' },
      ],
      specifications: [
        { name: 'Fragrance Family', value: 'Woody & Spicy Citrus' },
        { name: 'Top Notes', value: 'Calabrian Bergamot, Pepper' },
        { name: 'Base Notes', value: 'Papua New Guinean Vanilla, Ambroxan' },
      ],
      highlights: ['Iconic Luxury Fragrance', 'Long-Lasting Eau De Parfum Concentration', 'Refillable Glass Flacon'],
      tags: ['dior', 'perfume', 'fragrance', 'sauvage', 'luxury'],
    },
    {
      name: 'Jo Malone London Velvet Rose & Oud Cologne Intense (100ml)',
      slug: 'jo-malone-velvet-rose-and-oud-cologne',
      description: 'Dark Damask rose wrapped in smoky oud wood, spiked with clove and delicious praline. Magnetizing, decadent, and deeply opulent fragrance.',
      brand: 'Jo Malone',
      category: catBeauty._id,
      subCategory: subFragrances._id,
      images: [
        'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&q=80',
        'https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800&q=80',
      ],
      price: 15800,
      mrp: 17500,
      discount: 9,
      stock: 12,
      rating: 4.8,
      numReviews: 41,
      isNewArrival: true,
      variants: [
        { size: '50ml Spray', stock: 6, sku: 'JM-ROSE-50' },
        { size: '100ml Spray', stock: 6, sku: 'JM-ROSE-100' },
      ],
      specifications: [
        { name: 'Fragrance Family', value: 'Floral & Smoky Oud' },
        { name: 'Key Notes', value: 'Clove, Damask Rose, Smoky Oud Wood' },
        { name: 'Type', value: 'Cologne Intense' },
      ],
      highlights: ['Rich Damask Rose & Dark Oud', 'Long-Wearing Cologne Intense', 'Signature Gift Packaging'],
      tags: ['jomalone', 'perfume', 'fragrance', 'oud', 'rose'],
    },
    {
      name: 'Apple Watch Ultra 2 GPS + Cellular 49mm Titanium',
      slug: 'apple-watch-ultra-2-gps-cellular-49mm',
      description: 'The most capable and rugged Apple Watch. Designed for outdoor adventures and endurance workouts with a lightweight 49mm titanium case, extra-long battery life, and brightest display ever.',
      brand: 'Apple',
      category: catWatches._id,
      subCategory: subSmartwatches._id,
      images: [
        'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
        'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80',
      ],
      price: 89900,
      mrp: 89900,
      discount: 0,
      stock: 15,
      rating: 4.9,
      numReviews: 72,
      isFeatured: true,
      isBestSeller: true,
      variants: [
        { color: 'Titanium / Indigo Alpine Loop', size: 'Medium', stock: 8, sku: 'AWU2-IND-MED' },
        { color: 'Titanium / Orange Ocean Band', size: 'One Size', stock: 7, sku: 'AWU2-ORG-OCE' },
      ],
      specifications: [
        { name: 'Case Size', value: '49mm Aerospace-Grade Titanium' },
        { name: 'Display', value: '3000 nits Always-On Retina Display' },
        { name: 'Water Resistance', value: '100m Water Resistant / EN13319 Certified' },
      ],
      highlights: ['49mm Titanium Case & Sapphire Front', 'Up to 36 Hours Battery Life (72h Low Power)', 'Dual-Frequency Precision GPS'],
      tags: ['apple', 'smartwatch', 'ultra2', 'fitness', 'titanium'],
    },
    {
      name: 'Garmin Forerunner 965 Premium GPS Running Watch',
      slug: 'garmin-forerunner-965-premium-gps-running-watch',
      description: 'Train brilliantly with a colorful AMOLED touchscreen display, titanium bezel, full-color built-in maps, and advanced performance metrics tailored for runners and triathletes.',
      brand: 'Garmin',
      category: catSports._id,
      subCategory: subSmartwatches._id,
      images: [
        'https://images.unsplash.com/photo-1510017803434-a899398421b3?w=800&q=80',
        'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80',
      ],
      price: 67490,
      mrp: 74990,
      discount: 10,
      stock: 12,
      rating: 4.8,
      numReviews: 39,
      isTrending: true,
      variants: [
        { color: 'Black Titanium Bezel', stock: 7, sku: 'GAR-965-BLK' },
        { color: 'Amp Yellow Silicone Band', stock: 5, sku: 'GAR-965-YEL' },
      ],
      specifications: [
        { name: 'Display', value: '1.4-inch AMOLED (454 x 454 pixels)' },
        { name: 'Battery Life', value: 'Up to 23 days in smartwatch mode' },
        { name: 'GPS', value: 'Multi-Band SatIQ GPS Technology' },
      ],
      highlights: ['Vibrant 1.4" AMOLED Touchscreen', 'Full-Color Built-in TopoMaps', 'Training Readiness & HRV Status'],
      tags: ['garmin', 'running', 'gps', 'fitness', 'smartwatch'],
    },
    {
      name: 'Bowflex SelectTech 552 Adjustable Dumbbells (Pair)',
      slug: 'bowflex-selecttech-552-adjustable-dumbbells-pair',
      description: 'Replace 15 sets of weights with one compact system. Easily adjust from 5 lbs (2.2 kg) up to 52.5 lbs (24 kg) with a turn of a dial.',
      brand: 'Bowflex',
      category: catSports._id,
      subCategory: subFitness._id,
      images: [
        'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80',
        'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
      ],
      price: 34999,
      mrp: 49999,
      discount: 30,
      stock: 10,
      rating: 4.9,
      numReviews: 128,
      isBestSeller: true,
      variants: [
        { color: 'Black / Red Accents', weight: '5 to 52.5 lbs Pair', stock: 10, sku: 'BOW-552-PAIR' },
      ],
      specifications: [
        { name: 'Weight Range', value: '5 to 52.5 lbs (2.2 to 24 kg) per dumbbell' },
        { name: 'Adjustments', value: '15 Weight Settings in 2.5 lb Increments' },
        { name: 'Dimensions', value: '43 x 20 x 23 cm' },
      ],
      highlights: ['15 Weight Sets in 1 Compact Unit', 'Intuitive Dial Selection System', 'Durable Molded Metal Plates'],
      tags: ['dumbbells', 'fitness', 'gym', 'workout', 'bowflex'],
    },
    {
      name: 'Manduka PRO High-Density 6mm Yoga Mat',
      slug: 'manduka-pro-high-density-6mm-yoga-mat',
      description: 'The world famous #1 recommended yoga mat by teachers worldwide. Ultra-dense cushioning provides joint protection and unmatched longevity backed by a Lifetime Guarantee.',
      brand: 'Manduka',
      category: catSports._id,
      subCategory: subFitness._id,
      images: [
        'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80',
        'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80',
      ],
      price: 9999,
      mrp: 12999,
      discount: 23,
      stock: 25,
      rating: 4.8,
      numReviews: 55,
      isFeatured: true,
      variants: [
        { color: 'Black Sage', size: '71 inch x 26 inch', stock: 15, sku: 'MAN-PRO-SGE' },
        { color: 'Midnight Dark Blue', size: '71 inch x 26 inch', stock: 10, sku: 'MAN-PRO-BLU' },
      ],
      specifications: [
        { name: 'Thickness', value: '6 mm High-Density Cushioning' },
        { name: 'Material', value: '100% Latex-Free Closed-Cell PVC' },
        { name: 'Warranty', value: 'Lifetime Manufacturer Guarantee' },
      ],
      highlights: ['Unrivaled 6mm Joint Protection', 'Closed-Cell Surface Prevents Sweat Absorption', 'Lifetime Guarantee'],
      tags: ['yoga', 'mat', 'manduka', 'fitness', 'wellness'],
    },
    {
      name: 'Decathlon Kiprun Trail Running Hydration Backpack (10L)',
      slug: 'decathlon-kiprun-trail-running-hydration-backpack-10l',
      description: 'Ultra-lightweight 10-liter trail running vest designed with 11 ergonomic storage pockets and includes a 1.0L water bladder for endurance distance trail runs.',
      brand: 'Kiprun',
      category: catSports._id,
      subCategory: subSportsGear._id,
      images: [
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
        'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&q=80',
      ],
      price: 3999,
      mrp: 5999,
      discount: 33,
      stock: 30,
      rating: 4.7,
      numReviews: 48,
      isNewArrival: true,
      variants: [
        { size: 'S/M', color: 'Carbon Black', stock: 15, sku: 'KIP-VEST-SM' },
        { size: 'L/XL', color: 'Carbon Black', stock: 15, sku: 'KIP-VEST-LXL' },
      ],
      specifications: [
        { name: 'Capacity', value: '10 Liters Total Storage' },
        { name: 'Bladder Included', value: '1.0 Liter Hydration Bladder' },
        { name: 'Weight', value: '240g Empty' },
      ],
      highlights: ['11 Easily Accessible Compartments', 'Includes 1L Water Reservoir', 'Breathable Ergonomic Mesh Fit'],
      tags: ['trail', 'running', 'hydration', 'backpack', 'sports'],
    },
    {
      name: 'Seiko Presage Cocktail Time Automatic Mechanical Watch',
      slug: 'seiko-presage-cocktail-time-automatic-mechanical-watch',
      description: 'Inspired by classic cocktail bars, featuring a radiant sunburst guilloche dial, polished stainless steel case, box-shaped Hardlex crystal, and 4R35 automatic movement.',
      brand: 'Seiko',
      category: catWatches._id,
      subCategory: subLuxuryWatches._id,
      images: [
        'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80',
        'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=800&q=80',
      ],
      price: 42500,
      mrp: 49500,
      discount: 14,
      stock: 10,
      rating: 4.9,
      numReviews: 61,
      isFeatured: true,
      isBestSeller: true,
      variants: [
        { color: 'Ice Blue Sunburst (Skydiving)', stock: 5, sku: 'SEIKO-SRPB43' },
        { color: 'Deep Blue Sunburst (Manhattan)', stock: 5, sku: 'SEIKO-SRPS41' },
      ],
      specifications: [
        { name: 'Movement', value: 'Caliber 4R35 Automatic with Manual Winding' },
        { name: 'Case Diameter', value: '40.5 mm' },
        { name: 'Power Reserve', value: 'Approx. 41 Hours' },
      ],
      highlights: ['Exquisite Sunburst Dial Design', 'Seiko 4R35 Automatic Caliber', 'See-Through Exhibition Case Back'],
      tags: ['seiko', 'watch', 'automatic', 'presage', 'luxury'],
    },
    {
      name: 'Fossil Gen 6 Touchscreen Smartwatch with Wear OS',
      slug: 'fossil-gen-6-touchscreen-smartwatch',
      description: 'Powered by Snapdragon Wear 4100+ platform for 85% faster performance. Features fast charging to 80% in 30 minutes, continuous heart rate tracking, and SpO2 sensor.',
      brand: 'Fossil',
      category: catWatches._id,
      subCategory: subSmartwatches._id,
      images: [
        'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
        'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
      ],
      price: 18495,
      mrp: 24995,
      discount: 26,
      stock: 20,
      rating: 4.4,
      numReviews: 44,
      isTrending: true,
      variants: [
        { color: 'Smoke Stainless Steel', stock: 10, sku: 'FOS-GEN6-SMK' },
        { color: 'Black Silicone', stock: 10, sku: 'FOS-GEN6-BLK' },
      ],
      specifications: [
        { name: 'Processor', value: 'Qualcomm Snapdragon Wear 4100+' },
        { name: 'OS', value: 'Wear OS by Google' },
        { name: 'Charging', value: '80% in 30 Minutes' },
      ],
      highlights: ['Snapdragon 4100+ Ultra Fast Processor', 'SpO2 Blood Oxygen & Heart Rate Monitor', '30-Minute Rapid Fast Charge'],
      tags: ['fossil', 'smartwatch', 'wearos', 'watches'],
    },
    {
      name: 'Ray-Ban Aviator Classic Sunglasses (Gold Frame / G-15 Green)',
      slug: 'ray-ban-aviator-classic-sunglasses-gold-g15',
      description: 'Originally created for U.S. aviators in 1937. Iconic tear-drop shape gold metal frame paired with classic G-15 solid green crystal lenses providing 100% UV protection.',
      brand: 'Ray-Ban',
      category: catWatches._id,
      subCategory: subLuxuryWatches._id,
      images: [
        'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80',
        'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80',
      ],
      price: 9890,
      mrp: 11590,
      discount: 15,
      stock: 35,
      rating: 4.8,
      numReviews: 160,
      isBestSeller: true,
      variants: [
        { color: 'Arista Gold / G-15 Green Glass', size: '58mm Standard', stock: 20, sku: 'RB-3025-L0205' },
        { color: 'Matte Black / G-15 Green Glass', size: '58mm Standard', stock: 15, sku: 'RB-3025-002' },
      ],
      specifications: [
        { name: 'Frame Material', value: 'Corrosion-Resistant Metal' },
        { name: 'Lens Tech', value: 'G-15 Crystal Glass (Absorbs 85% Visible Light)' },
        { name: 'UV Protection', value: '100% UV400 Protection' },
      ],
      highlights: ['100% Original Timeless Aviator Design', 'G-15 Natural Vision Crystal Lenses', 'Made in Italy'],
      tags: ['rayban', 'aviator', 'sunglasses', 'eyewear', 'fashion'],
    },
    {
      name: 'Tommy Hilfiger Genuine Leather Bifold Wallet',
      slug: 'tommy-hilfiger-genuine-leather-bifold-wallet',
      description: 'Handcrafted from 100% genuine cowhide leather with RFID blocking technology. Features 6 card slots, 2 bill compartments, and removable ID window passcase.',
      brand: 'Tommy Hilfiger',
      category: catFashion._id,
      subCategory: subMen._id,
      images: [
        'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
        'https://images.unsplash.com/photo-1606503830018-a664e4395462?w=800&q=80',
      ],
      price: 1999,
      mrp: 3499,
      discount: 43,
      stock: 50,
      rating: 4.6,
      numReviews: 89,
      isBestSeller: true,
      variants: [
        { color: 'Classic Tan Brown', stock: 25, sku: 'TH-WLT-TAN' },
        { color: 'Midnight Black', stock: 25, sku: 'TH-WLT-BLK' },
      ],
      specifications: [
        { name: 'Material', value: '100% Genuine Full-Grain Leather' },
        { name: 'Security', value: 'Built-in RFID Shielding Lining' },
        { name: 'Capacity', value: '6 Card Slots, 2 Currency Slots' },
      ],
      highlights: ['100% Premium Cowhide Leather', 'Advanced RFID Blocking Security', 'Signature Tommy Flag Emblem'],
      tags: ['wallet', 'leather', 'tommy', 'accessories', 'men'],
    },
    {
      name: 'Peak Design Everyday Backpack 20L (V2)',
      slug: 'peak-design-everyday-backpack-20l-v2',
      description: 'An iconic, award-winning pack built for everyday carry and camera gear protection. Features weatherproof MagLatch hardware, dual side access zips, and FlexFold dividers.',
      brand: 'Peak Design',
      category: catWatches._id,
      subCategory: subLuxuryWatches._id,
      images: [
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
        'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&q=80',
      ],
      price: 24999,
      mrp: 28999,
      discount: 14,
      stock: 12,
      rating: 4.9,
      numReviews: 36,
      isFeatured: true,
      variants: [
        { color: 'Charcoal Black 20L', stock: 6, sku: 'PD-EDB-20-CHA' },
        { color: 'Midnight Navy 20L', stock: 6, sku: 'PD-EDB-20-NAV' },
      ],
      specifications: [
        { name: 'Capacity', value: '20 Liters (Expandable)' },
        { name: 'Laptop Fit', value: 'Fits up to 15.6 inch Laptops' },
        { name: 'Fabric', value: 'Weatherproof 400D Double Poly-Coated Nylon Canvas' },
      ],
      highlights: ['Patent-Pending MagLatch Top Closure', 'Configurable FlexFold Gear Dividers', '100% Recycled Weatherproof Shell'],
      tags: ['peakdesign', 'backpack', 'camera', 'travel', 'accessories'],
    },
    {
      name: 'Sony PlayStation 5 Slim Console (Disc Edition)',
      slug: 'sony-playstation-5-slim-console-disc-edition',
      description: 'Unleash new gaming possibilities with the slim PS5 console. Experience lightning fast loading with ultra-high speed SSD, deeper immersion with haptic feedback and 3D Audio.',
      brand: 'Sony',
      category: catElectronics._id,
      subCategory: subComputers._id,
      images: [
        'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&q=80',
        'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&q=80',
      ],
      price: 54990,
      mrp: 54990,
      discount: 0,
      stock: 10,
      rating: 4.9,
      numReviews: 210,
      isFeatured: true,
      isBestSeller: true,
      variants: [
        { color: 'Standard White', size: '1TB Custom SSD', stock: 10, sku: 'PS5-SLM-DISC' },
      ],
      specifications: [
        { name: 'Storage', value: '1TB Custom Ultra-Fast NVMe SSD' },
        { name: 'Output', value: '4K 120Hz / 8K HDR Support' },
        { name: 'Controller', value: 'DualSense Wireless Controller Included' },
      ],
      highlights: ['Ultra-High Speed 1TB NVMe SSD', 'DualSense Haptic Feedback & Adaptive Triggers', 'Ray Tracing & 4K 120Hz Output'],
      tags: ['sony', 'ps5', 'playstation', 'gaming', 'console'],
    },
    {
      name: 'Nintendo Switch OLED Model White Set',
      slug: 'nintendo-switch-oled-model-white-set',
      description: 'Features a vibrant 7-inch OLED screen, wide adjustable stand, wired LAN port dock, 64 GB internal storage, and enhanced audio in tabletop and handheld mode.',
      brand: 'Nintendo',
      category: catElectronics._id,
      subCategory: subComputers._id,
      images: [
        'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&q=80',
        'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&q=80',
      ],
      price: 31999,
      mrp: 37999,
      discount: 16,
      stock: 15,
      rating: 4.8,
      numReviews: 115,
      isTrending: true,
      variants: [
        { color: 'Joy-Con White', stock: 10, sku: 'NSW-OLED-WHT' },
        { color: 'Neon Red / Neon Blue', stock: 5, sku: 'NSW-OLED-NEO' },
      ],
      specifications: [
        { name: 'Display', value: '7.0-inch OLED Capacitive Touchscreen (1280x720)' },
        { name: 'Storage', value: '64 GB Internal (Expandable up to 2TB)' },
        { name: 'Modes', value: 'TV Mode, Tabletop Mode, Handheld Mode' },
      ],
      highlights: ['Vibrant 7-inch OLED Screen', 'Wide Adjustable Stand', 'Wired LAN Port in Dock'],
      tags: ['nintendo', 'switch', 'oled', 'gaming', 'handheld'],
    },
    {
      name: 'Logitech MX Master 3S Wireless Performance Mouse',
      slug: 'logitech-mx-master-3s-wireless-mouse',
      description: 'An iconic mouse remastered with Quiet Clicks and 8,000 DPI track-on-glass sensor. MagSpeed electromagnetic scrolling delivers 1,000 lines per second.',
      brand: 'Logitech',
      category: catElectronics._id,
      subCategory: subComputers._id,
      images: [
        'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80',
        'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80',
      ],
      price: 9495,
      mrp: 10995,
      discount: 14,
      stock: 30,
      rating: 4.9,
      numReviews: 145,
      isBestSeller: true,
      variants: [
        { color: 'Graphite', stock: 15, sku: 'MX-MSTR3S-GRP' },
        { color: 'Pale Grey', stock: 15, sku: 'MX-MSTR3S-GRY' },
      ],
      specifications: [
        { name: 'Sensor DPI', value: '200 to 8000 DPI (Track on Glass)' },
        { name: 'Scroll Wheel', value: 'MagSpeed Electromagnetic Scrolling' },
        { name: 'Battery', value: '70 Days Full Charge / 3 Hours from 1 Min Charge' },
      ],
      highlights: ['8,000 DPI Any-Surface Tracking', '90% Quieter Click Technology', 'MagSpeed Ultra-Fast Scrolling'],
      tags: ['logitech', 'mouse', 'mxmaster', 'wireless', 'productivity'],
    },
    {
      name: 'Keychron K2 V2 Wireless Mechanical Keyboard (RGB Backlit)',
      slug: 'keychron-k2-v2-wireless-mechanical-keyboard',
      description: 'A 75% layout compact Bluetooth mechanical keyboard engineered for Mac and Windows. Connects up to 3 devices simultaneously with Gateron G Pro switches.',
      brand: 'Keychron',
      category: catElectronics._id,
      subCategory: subComputers._id,
      images: [
        'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
        'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&q=80',
      ],
      price: 8499,
      mrp: 11999,
      discount: 29,
      stock: 20,
      rating: 4.7,
      numReviews: 78,
      isTrending: true,
      variants: [
        { color: 'RGB Aluminum Frame', switch: 'Gateron G Pro Brown', stock: 10, sku: 'K2-ALU-BRN' },
        { color: 'RGB Aluminum Frame', switch: 'Gateron G Pro Red', stock: 10, sku: 'K2-ALU-RED' },
      ],
      specifications: [
        { name: 'Layout', value: '75% Compact (84 Keys)' },
        { name: 'Connectivity', value: 'Bluetooth 5.1 & Type-C Wired' },
        { name: 'Battery', value: '4000 mAh Rechargeable Battery' },
      ],
      highlights: ['Dual Mac & Windows Keycap Layout', 'Hot-Swappable Gateron Switches', '4000mAh Battery Power'],
      tags: ['keychron', 'keyboard', 'mechanical', 'wireless', 'rgb'],
    },
    {
      name: 'Samsung Odyssey G7 32-inch 240Hz Curved Gaming Monitor',
      slug: 'samsung-odyssey-g7-32-inch-240hz-curved-gaming-monitor',
      description: 'World-first 1000R curvature matches human eye field of view. Features 240Hz refresh rate, 1ms response time, QLED QHD resolution, and Nvidia G-Sync compatibility.',
      brand: 'Samsung',
      category: catElectronics._id,
      subCategory: subComputers._id,
      images: [
        'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80',
        'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=800&q=80',
      ],
      price: 49999,
      mrp: 68000,
      discount: 26,
      stock: 8,
      rating: 4.8,
      numReviews: 40,
      isFeatured: true,
      variants: [
        { size: '32-inch QHD', color: 'Matte Black Core Lighting', stock: 8, sku: 'SAM-G7-32-QHD' },
      ],
      specifications: [
        { name: 'Resolution', value: 'QHD (2560 x 1440) QLED' },
        { name: 'Refresh Rate', value: '240 Hz' },
        { name: 'Curvature', value: '1000R Deep Curve' },
      ],
      highlights: ['1000R Eye-Matching Curvature', '240Hz Refresh Rate & 1ms GTG', 'NVIDIA G-Sync & FreeSync Premium Pro'],
      tags: ['samsung', 'monitor', 'gaming', '240hz', 'curved'],
    },
    {
      name: 'Puma RS-X3 Puzzle Unisex Retro Sneakers',
      slug: 'puma-rs-x3-puzzle-unisex-retro-sneakers',
      description: 'Puma takes retro sneaker design to another level with RS-X3 Puzzle. Features amplified tech detailing, bold color contrast mesh upper, and soft cushioned RS technology midsole.',
      brand: 'Puma',
      category: catFashion._id,
      subCategory: subFootwear._id,
      images: [
        'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
        'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80',
      ],
      price: 5599,
      mrp: 9999,
      discount: 44,
      stock: 30,
      rating: 4.5,
      numReviews: 67,
      isTrending: true,
      variants: [
        { size: 'UK 8', color: 'White / Royal Blue / High Risk Red', stock: 10, sku: 'PUM-RSX-08' },
        { size: 'UK 9', color: 'White / Royal Blue / High Risk Red', stock: 12, sku: 'PUM-RSX-09' },
        { size: 'UK 10', color: 'White / Royal Blue / High Risk Red', stock: 8, sku: 'PUM-RSX-10' },
      ],
      specifications: [
        { name: 'Upper', value: 'Mesh Upper with Leather & Suede Overlays' },
        { name: 'Midsole', value: 'Puma Running System Cushioning Tech' },
        { name: 'Outsole', value: 'Full Rubber Traction Outsole' },
      ],
      highlights: ['Retro Chunky Silhouette', 'Soft Running System Midsole', 'Multi-Material Layered Upper'],
      tags: ['puma', 'sneakers', 'retro', 'footwear', 'fashion'],
    },
    {
      name: 'Under Armour HeatGear Compression Base Layer Top',
      slug: 'under-armour-heatgear-compression-base-layer-top',
      description: 'Ultra-tight, second-skin fit base layer built with HeatGear fabric that wicks sweat, dries fast, and features 4-way stretch construction for maximum mobility during workouts.',
      brand: 'Under Armour',
      category: catFashion._id,
      subCategory: subMen._id,
      images: [
        'https://images.unsplash.com/photo-1506152983158-b4a74a01c721?w=800&q=80',
        'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&q=80',
      ],
      price: 1999,
      mrp: 2999,
      discount: 33,
      stock: 40,
      rating: 4.7,
      numReviews: 82,
      isBestSeller: true,
      variants: [
        { size: 'M', color: 'Tactical Black', stock: 15, sku: 'UA-HG-M-BLK' },
        { size: 'L', color: 'Tactical Black', stock: 15, sku: 'UA-HG-L-BLK' },
        { size: 'XL', color: 'Tactical Black', stock: 10, sku: 'UA-HG-XL-BLK' },
      ],
      specifications: [
        { name: 'Fabric', value: '84% Polyester, 16% Elastane HeatGear' },
        { name: 'Fit', value: 'Ultra-Tight Compression' },
        { name: 'Tech', value: 'Anti-Odor Technology' },
      ],
      highlights: ['Sweat-Wicking Fast-Drying HeatGear', '4-Way Stretch Flexibility', 'Anti-Odor Microbe Prevention'],
      tags: ['underarmour', 'fitness', 'gym', 'compression', 'men'],
    },
    {
      name: 'H&M Relaxed Fit Pure Linen Blend Shirt',
      slug: 'hm-relaxed-fit-pure-linen-blend-shirt',
      description: 'Airy woven shirt made from soft linen and cotton blend. Features resort turn-down collar, smooth French front button placket, and relaxed easy silhouette.',
      brand: 'H&M',
      category: catFashion._id,
      subCategory: subMen._id,
      images: [
        'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
        'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80',
      ],
      price: 1799,
      mrp: 2699,
      discount: 33,
      stock: 35,
      rating: 4.5,
      numReviews: 50,
      isNewArrival: true,
      variants: [
        { size: 'M', color: 'Sand Beige', stock: 15, sku: 'HM-LIN-M-BGE' },
        { size: 'L', color: 'Sand Beige', stock: 15, sku: 'HM-LIN-L-BGE' },
        { size: 'XL', color: 'Sand Beige', stock: 5, sku: 'HM-LIN-XL-BGE' },
      ],
      specifications: [
        { name: 'Material', value: '55% Linen, 45% Cotton' },
        { name: 'Collar', value: 'Resort Camp Collar' },
        { name: 'Care', value: 'Machine Wash 40°C' },
      ],
      highlights: ['Lightweight Breathable Linen Blend', 'Effortless Resort Fit', 'Natural Soft Texture'],
      tags: ['hm', 'shirt', 'linen', 'men', 'casual'],
    },
    {
      name: 'Forever 21 High-Waisted Wide Leg Tailored Trousers',
      slug: 'forever-21-high-waisted-wide-leg-tailored-trousers',
      description: 'Sophisticated pleated trousers cut with a high-rise waistline, wide flared legs, front side slash pockets, and sleek zip fly hook-and-bar closure.',
      brand: 'Forever 21',
      category: catFashion._id,
      subCategory: subWomen._id,
      images: [
        'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80',
        'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80',
      ],
      price: 2199,
      mrp: 3499,
      discount: 37,
      stock: 25,
      rating: 4.6,
      numReviews: 34,
      isTrending: true,
      variants: [
        { size: 'S', color: 'Camel Brown', stock: 10, sku: 'F21-TRSR-S-CML' },
        { size: 'M', color: 'Camel Brown', stock: 10, sku: 'F21-TRSR-M-CML' },
        { size: 'L', color: 'Camel Brown', stock: 5, sku: 'F21-TRSR-L-CML' },
      ],
      specifications: [
        { name: 'Fabric', value: '78% Polyester, 18% Rayon, 4% Spandex' },
        { name: 'Rise', value: 'High Rise (12 inches)' },
        { name: 'Leg Shape', value: 'Wide Leg Flared' },
      ],
      highlights: ['Chic High-Waisted Silhouette', 'Double Front Pleat Detailing', 'Wrinkle-Resistant Crepe Stretch'],
      tags: ['women', 'trousers', 'wideleg', 'fashion', 'forever21'],
    },
    {
      name: 'Calvin Klein Cotton Stretch Boxer Briefs (3-Pack)',
      slug: 'calvin-klein-cotton-stretch-boxer-briefs-3pack',
      description: 'Designed with ultra-soft cotton blended with elastane for shape retention. Iconic Calvin Klein logo repeating elastic waistband and contoured pouch.',
      brand: 'Calvin Klein',
      category: catFashion._id,
      subCategory: subMen._id,
      images: [
        'https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=800&q=80',
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80',
      ],
      price: 2499,
      mrp: 3999,
      discount: 37,
      stock: 50,
      rating: 4.8,
      numReviews: 190,
      isBestSeller: true,
      variants: [
        { size: 'M', color: 'Black / Grey / White 3-Pack', stock: 25, sku: 'CK-BB-3P-M' },
        { size: 'L', color: 'Black / Grey / White 3-Pack', stock: 25, sku: 'CK-BB-3P-L' },
      ],
      specifications: [
        { name: 'Fabric', value: '95% Cotton, 5% Elastane' },
        { name: 'Waistband', value: 'Microfiber Jacquard Elastic' },
        { name: 'Quantity', value: '3 Boxer Briefs per Pack' },
      ],
      highlights: ['Original Calvin Klein Signature Logo', 'Soft Stretch Breathable Cotton', 'Shape Retention Elasticity'],
      tags: ['calvinklein', 'undergarments', 'men', 'cotton'],
    },
    {
      name: 'Dyson V15 Detect Cordless Smart Vacuum Cleaner',
      slug: 'dyson-v15-detect-cordless-smart-vacuum-cleaner',
      description: 'Dyson’s most powerful intelligent cordless vacuum. Features a laser that reveals microscopic dust, piezo sensor that counts dust particles, and up to 60 minutes runtime.',
      brand: 'Dyson',
      category: catHome._id,
      subCategory: subFurniture._id,
      images: [
        'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80',
        'https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80',
      ],
      price: 62900,
      mrp: 69900,
      discount: 10,
      stock: 7,
      rating: 4.9,
      numReviews: 83,
      isFeatured: true,
      variants: [
        { color: 'Yellow / Nickel', stock: 7, sku: 'DYS-V15-YEL' },
      ],
      specifications: [
        { name: 'Suction Power', value: '230 AW (Air Watts)' },
        { name: 'Run Time', value: 'Up to 60 Minutes' },
        { name: 'Filtration', value: '99.99% Whole-Machine HEPA Filtration' },
      ],
      highlights: ['Laser Slim Fluffy Cleaner Head', 'Piezo Sensor Particle Counter', '230AW Powerful Hyperdymium Motor'],
      tags: ['dyson', 'vacuum', 'cleaner', 'home', 'appliances'],
    },
    {
      name: "Nespresso Vertuo Pop Coffee Machine by De'Longhi",
      slug: 'nespresso-vertuo-pop-coffee-machine',
      description: 'Compact single-serve espresso and coffee maker using Centrifusion technology to produce rich crema across 5 cup sizes at the touch of a single button.',
      brand: 'Nespresso',
      category: catHome._id,
      subCategory: subKitchen._id,
      images: [
        'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&q=80',
        'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80',
      ],
      price: 12999,
      mrp: 16999,
      discount: 23,
      stock: 18,
      rating: 4.7,
      numReviews: 58,
      isTrending: true,
      variants: [
        { color: 'Pacific Blue', stock: 9, sku: 'NES-VPOP-BLU' },
        { color: 'Mango Yellow', stock: 9, sku: 'NES-VPOP-YEL' },
      ],
      specifications: [
        { name: 'Technology', value: 'Centrifusion Extraction Barcode Technology' },
        { name: 'Heat Up Time', value: '30 Seconds' },
        { name: 'Cup Sizes', value: '5 Sizes (Espresso to Alto)' },
      ],
      highlights: ['Patented Centrifusion Brewing', 'One-Touch Automatic Barcode Reading', 'Compact Colorful Design'],
      tags: ['nespresso', 'coffee', 'espresso', 'kitchen'],
    },
    {
      name: 'Philips Smart Wi-Fi LED Color Changing Light Bulb (Pack of 3)',
      slug: 'philips-smart-wifi-led-color-changing-light-bulb-pack-of-3',
      description: 'Control your lighting from anywhere using the Wiz app or voice commands via Alexa & Google Assistant. Features 16 million colors and adjustable warm-to-cool white tones.',
      brand: 'Philips',
      category: catHome._id,
      subCategory: subFurniture._id,
      images: [
        'https://images.unsplash.com/photo-1550985616-10810253b84d?w=800&q=80',
        'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
      ],
      price: 1999,
      mrp: 3499,
      discount: 43,
      stock: 60,
      rating: 4.6,
      numReviews: 130,
      isBestSeller: true,
      variants: [
        { color: '16 Million RGB Colors 9W', holder: 'B22 Base', stock: 30, sku: 'PHI-WIZ-B22-3P' },
        { color: '16 Million RGB Colors 9W', holder: 'E27 Base', stock: 30, sku: 'PHI-WIZ-E27-3P' },
      ],
      specifications: [
        { name: 'Power', value: '9 Watts (825 Lumens equivalent to 60W)' },
        { name: 'Connectivity', value: '2.4GHz Wi-Fi + Bluetooth (No Hub Required)' },
        { name: 'Compatibility', value: 'Amazon Alexa, Google Assistant, Siri Shortcuts' },
      ],
      highlights: ['16 Million Colors & Dynamic Light Modes', 'Voice Control via Alexa & Google', 'No Hub Required'],
      tags: ['philips', 'smartlight', 'home', 'led', 'automation'],
    },
    {
      name: 'Marshall Stanmore III Wireless Bluetooth Home Speaker',
      slug: 'marshall-stanmore-iii-wireless-bluetooth-home-speaker',
      description: 'Iconic vintage Marshall design re-engineered with a wider soundstage. Outward-angled tweeters and updated waveguides deliver an immersive room-filling analog sound experience.',
      brand: 'Marshall',
      category: catElectronics._id,
      subCategory: subAudio._id,
      images: [
        'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80',
        'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
      ],
      price: 31999,
      mrp: 39999,
      discount: 20,
      stock: 14,
      rating: 4.9,
      numReviews: 95,
      isFeatured: true,
      variants: [
        { color: 'Iconic Black Vinyl', stock: 8, sku: 'MSH-STAN3-BLK' },
        { color: 'Vintage Cream', stock: 6, sku: 'MSH-STAN3-CRM' },
      ],
      specifications: [
        { name: 'Power Amplifiers', value: '50W Class D (Woofer) + Two 15W Class D (Tweeters)' },
        { name: 'Bluetooth', value: 'Bluetooth 5.2 with LE Audio' },
        { name: 'Inputs', value: '3.5mm Aux & RCA Inputs' },
      ],
      highlights: ['Re-Engineered Wider Soundstage', 'Classic Brass Analog Knobs', '70% Recycled PVC-Free Vegan Materials'],
      tags: ['marshall', 'speaker', 'bluetooth', 'audio', 'vintage'],
    },
    {
      name: 'Philips Series 7000 Wet & Dry Electric Shaver with Beard Trimmer',
      slug: 'philips-series-7000-wet-dry-electric-shaver',
      description: 'Glides smoothly over skin while cutting each hair close with SkinIQ technology. Microbead SkinGlide coating reduces skin friction for maximum comfort.',
      brand: 'Philips',
      category: catBeauty._id,
      subCategory: subSkincare._id,
      images: [
        'https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80',
        'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
      ],
      price: 7499,
      mrp: 11995,
      discount: 37,
      stock: 22,
      rating: 4.7,
      numReviews: 53,
      isTrending: true,
      variants: [
        { color: 'Dark Chrome Blue', stock: 22, sku: 'PHI-S7000-BLU' },
      ],
      specifications: [
        { name: 'Blades', value: '45 Self-Sharpening SteelPrecision Blades' },
        { name: 'Battery', value: '60 Minutes Cordless Use / 1 Hour Charge' },
        { name: 'Cleaning', value: 'Quick Clean Pod & Fully Washable' },
      ],
      highlights: ['SkinGlide Protective Coating', '360-D Flexible Shaving Heads', 'Wet & Dry Operation'],
    },
  ];

  const formattedProductsData = productsData.map((prod) => {
    let imgs = (prod.images || []).filter(Boolean);
    if (imgs.length > 0 && imgs.length < 4) {
      imgs = Array.from({ length: 4 }, (_, i) => imgs[i % imgs.length]);
    }
    return { ...prod, images: imgs };
  });

  const createdProducts = await Product.insertMany(formattedProductsData);
  console.log(`[seed] Created ${createdProducts.length} rich catalog products...`);

  // 5. Create Hero & Promo Banners
  await Banner.insertMany([
    {
      title: 'The Mega Festive Sale is Live',
      subtitle: 'Up to 60% Off on Top Electronics, Audio & Gadgets',
      image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1600&q=80',
      link: '/products?category=electronics',
      buttonText: 'Explore Gadgets',
      badge: 'Festive Special',
      position: 'home_hero',
      displayOrder: 1,
      isActive: true,
    },
    {
      title: 'Curated Autumn Collection 2026',
      subtitle: 'Refined menswear, elevated casuals & premium sneakers',
      image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1600&q=80',
      link: '/products?category=fashion',
      buttonText: 'Shop New Arrivals',
      badge: 'New Season',
      position: 'home_hero',
      displayOrder: 2,
      isActive: true,
    },
    {
      title: 'Elevate Your Sanctuary',
      subtitle: 'Modern Scandinavian furniture, artisanal cookware & home accents',
      image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1600&q=80',
      link: '/products?category=home-and-living',
      buttonText: 'Upgrade Home',
      badge: 'Interior Trends',
      position: 'home_hero',
      displayOrder: 3,
      isActive: true,
    },
    {
      title: 'Weekend Flash Offer: Flat ₹500 OFF',
      subtitle: 'Use code WELCOME50 on your first cart order above ₹999',
      image: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=1200&q=80',
      link: '/products',
      buttonText: 'Claim Offer',
      badge: 'Limited Time',
      position: 'home_promo',
      displayOrder: 1,
      isActive: true,
    },
  ]);

  console.log('[seed] Created promotional banners...');

  // 6. Create Coupons
  const nextMonth = new Date();
  nextMonth.setDate(nextMonth.getDate() + 45);
  const prevMonth = new Date();
  prevMonth.setDate(prevMonth.getDate() - 10);

  await Coupon.insertMany([
    {
      code: 'WELCOME50',
      discountType: 'percentage',
      discountValue: 50,
      minOrderValue: 999,
      maxDiscount: 500,
      startDate: prevMonth,
      expiryDate: nextMonth,
      usageLimit: 1000,
      usedCount: 14,
      isActive: true,
    },
    {
      code: 'AMA20',
      discountType: 'percentage',
      discountValue: 20,
      minOrderValue: 2000,
      maxDiscount: 1000,
      startDate: prevMonth,
      expiryDate: nextMonth,
      usageLimit: 500,
      usedCount: 28,
      isActive: true,
    },
    {
      code: 'FREESHIP',
      discountType: 'freeDelivery',
      discountValue: 0,
      minOrderValue: 0,
      startDate: prevMonth,
      expiryDate: nextMonth,
      usageLimit: 2000,
      usedCount: 42,
      isActive: true,
    },
    {
      code: 'FESTIVE100',
      discountType: 'fixed',
      discountValue: 100,
      minOrderValue: 500,
      startDate: prevMonth,
      expiryDate: nextMonth,
      usageLimit: 500,
      usedCount: 5,
      isActive: true,
    },
  ]);

  console.log('[seed] Created discount coupons...');

  // 7. Create Sample Reviews
  const pSony = createdProducts[0];
  const pNike = createdProducts[3];

  await Review.insertMany([
    {
      product: pSony._id,
      user: demoUser._id,
      rating: 5,
      comment: 'Absolutely phenomenal sound signature and the noise cancellation is unmatched. Battery easily lasts days!',
      isVerifiedPurchase: true,
      isApproved: true,
    },
    {
      product: pNike._id,
      user: demoUser._id,
      rating: 5,
      comment: 'Super comfortable for all-day walking and daily jogging. Great cushion in the heel.',
      isVerifiedPurchase: true,
      isApproved: true,
    },
  ]);

  // 8. Create Sample Order for Demo User
  const sampleOrder = await Order.create({
    orderNumber: `AY-${Date.now().toString().slice(-4)}-104829`,
    user: demoUser._id,
    items: [
      {
        product: pSony._id,
        name: pSony.name,
        image: pSony.images[0],
        variant: { color: 'Midnight Black' },
        quantity: 1,
        price: pSony.price,
      },
      {
        product: pNike._id,
        name: pNike.name,
        image: pNike.images[0],
        variant: { size: 'UK 8', color: 'Crimson Red' },
        quantity: 1,
        price: pNike.price,
      },
    ],
    shippingAddress: {
      fullName: 'Rahul Sharma',
      phone: '+91 9811223344',
      line1: 'Flat 402, Sunshine Heights, MG Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      country: 'India',
      addressType: 'Home',
    },
    paymentInfo: {
      provider: 'card',
      paymentId: 'PAY-SAMPLE-9921',
      method: 'Credit Card',
      status: 'paid',
    },
    status: 'shipped',
    statusHistory: [
      { status: 'placed', note: 'Order placed by customer', at: new Date(Date.now() - 36 * 3600 * 1000) },
      { status: 'confirmed', note: 'Payment verified successfully', at: new Date(Date.now() - 35 * 3600 * 1000) },
      { status: 'processing', note: 'Item packaged in warehouse', at: new Date(Date.now() - 20 * 3600 * 1000) },
      { status: 'shipped', note: 'Handed over to BlueDart Courier (AWB: BLU882910)', at: new Date(Date.now() - 6 * 3600 * 1000) },
    ],
    subtotal: pSony.price + pNike.price,
    productDiscount: (pSony.mrp - pSony.price) + (pNike.mrp - pNike.price),
    couponDiscount: 500,
    couponCode: 'WELCOME50',
    deliveryCharge: 0,
    tax: Math.round((pSony.price + pNike.price) * 0.05),
    total: Math.round(pSony.price + pNike.price - 500 + (pSony.price + pNike.price) * 0.05),
  });

  // 9. Create Notifications
  await Notification.create({
    user: demoUser._id,
    type: 'order',
    title: 'Order Dispatched!',
    message: `Your order #${sampleOrder.orderNumber} is now on its way via BlueDart Express.`,
    isRead: false,
  });

  console.log('[seed] Seeding complete!');
  return { success: true };
}

// Standalone execution
if (require.main === module) {
  const env = require('./config/env');
  mongoose
    .connect(env.mongoUri)
    .then(async () => {
      console.log('[seed] Connected to MongoDB for manual seed');
      await seedData();
      await mongoose.disconnect();
      process.exit(0);
    })
    .catch((err) => {
      console.error('[seed] Manual seed error:', err.message);
      process.exit(1);
    });
}

module.exports = { seedData };
